language: node_js
os:
  - linux
  - osx
  - windows
node_js: # a good example: https://github.com/pillarjs/router/blob/master/.travis.yml
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - lts/*
  - node
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - test ! -d node_modules || npm prune
scripts:
  - npm run test
  - npm run build
# after_script:
#   - test $TRAVIS_NODE_VERSION == '12' && sonar-scanner
notifications:
  email:
    recipients:
      - dragos.cirjan@gmail.com
    on_success: never
    on_failure: always
# addons:
#   sonarcloud:
#     organization: "organisation"
#     token:
#       secure: "secure"

