language: node_js
os:
- linux
- osx
- windows
node_js:
- '10'
- '11'
- '12'
- '13'
- '14'
- lts/*
- node
sudo: false
cache:
  directories:
  - node_modules
before_script:
- test ! -d node_modules || npm prune
scripts:
- npm run test
- npm run build
after_script:
- test $TRAVIS_NODE_VERSION == '12' && test $TRAVIS_OS_NAME == 'linux' && sonar-scanner
notifications:
  email:
    recipients:
    - dragos.cirjan@gmail.com
    on_success: never
    on_failure: always
addons:
  sonarcloud:
    organization: mists-aside
    token:
      secure: WlxoMMZGNpv/IQCqBXNLJClQkL2rseP8mclRRJh4N60bfhhsS58xwyh/KHUjpDN+7zZG/bP/v1L/1CDU7loLnsQPB2f8UeNecukaYx12dRixkKm2WiWXbQHDweZdFpDq/F5dqmbCsDC+LTmaBmhlddJCafXgXM8pVEXYAHZx6A+YluTDAOPE1MMEZlgpjB32sLnMFPiSeW2Ov9WtoTigIG2jpvoBXKJztcTXdn8QdKoxK+19nkReA3UxKHhajMt/xo9+85sqtRXyIumuk0x6iP0256SyjidOY/joQiD9GmmJLPILkWjEH/I6q0Z4eHutiGDwdZ2PCnmcF+cQB2qPssnl+JxHXQcKeFp05aa7GSDGyJezLCPbbX0c1tZZmHP/qKuwFyIK8QRbkwy9+7A5a2sY+YQOqZI8UO5kBmI9uEKF32ofIu/Nnz1BWobHcytWRclK34Cdd1MGFLRBA34j9TpiyuSIGG6bDxei+QVm80QF9MpX86kJm+Z9VoSL0VJZMs17osy1nF1xTBKlrEaOjA/BVRRzYoYvxF8XUFUd76FB5GrcGwNJD5V8C6G6Mn/ihF2SyQlOQkl3aAmuqY8pJIIFQLGhT1DD1p9UjB+h4TTlmq30lbMi9PPgQSzKihIm6/JVBLcoyuQZW4hNPKmYq6fa7/S2CfPMFi4pLwjVcDQ=
deploy:
  provider: npm
  email: dragos.cirjan@gmail.com
  api_key:
    secure: kKHD3w0+ZDC3+SxFrYez+au92jmn9gf0rTigCJd/Z5HAxupY1BSKncHnrvJqkQzczx4riaU4YVTiiBy0DWZobpddTQilsgFwy9+HNVcBoFqNWZ+G2jo3KBtTDGQv9tBC2gLrtKacWeKi7LFIdZXp7DFOMg54wNvOdhakfYIr7VuQPJNg0Z4nzdfU+718rzL40Yrq2TXW10Ycz2I+OQYOKTtCiFI3zP5YsraCJ0Sn0j3CMoTmzIpC7o+xb2aktOs3ytEjzWAEdZiQNQoFNFuqaYQ12NWfbpByMPxPhWTZ9L4oAtfReza0WEBUcyY2uATjhkgVDb1uxRtDybehu5WObkn/XOqJHIYPRw6ytSKnRXJnUvbxQeHGHB8MzM+iK47hEw07QD3wToMFgEVPjb/BSKN1Qv1tHhLVS3O2tv5RCgKyiyUAM5hfJwT57oKd5S+2GGYxzzjqMjVogUPT7RprLRHUt4huxOVCKEkl05Wr936kfyB2ACPNbNOTAESx5InPctRTvHTBOC2OZaVU7tTFGENXgSIk8NlHjyUQKcFwKQjaIzxRwEDUwQ/Ao4g/TMta0qAsm9ERDtOuqxzWZp6l5Dp/RRfc0Ik718Rv3LV12zZ7KJDJ6uwFcC3KdVfdst+6rCSxhWrsEshy2ZCbH0tMhk+CWMcqajlK0LOu10tdZ/Y=
  on:
    tags: true
    repo: mists-aside/tempjs
  skip_cleanup: 'true'
